import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import bdCommerceLogo from "../public/Group.png";
import { FiPhone } from "react-icons/fi";
import { FiMenu } from "react-icons/fi";
import { MdKeyboardArrowUp } from "react-icons/md";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative `}
      >
        <div className="backdrop-blur-md fixed top-0 py-4 w-full shadow-lg">
          <nav className="flex justify-between items-center w-10/12 mx-auto ">
            <div className="relative md:hidden flex">
              <div>
                <FiMenu />
              </div>
              <div className="flex  absolute bottom-0">
                <Link className="hover:text-[#FB5C12]" href="/">
                  ইকমার্স
                </Link>
                <Link href="/">ফিচার</Link>
                <Link href="/">মূল্য </Link>
                <Link href="/">টুলস</Link>
                <Link href="/">ডেমো</Link>
              </div>
            </div>
            <div>
              <Image src={bdCommerceLogo} alt="bdCommerce" />
            </div>
            <div className="md:flex hidden gap-x-8  ">
              <Link className="hover:text-[#FB5C12]" href="/">
                ইকমার্স
              </Link>
              <Link href="/">ফিচার</Link>
              <Link href="/">মূল্য</Link>
              <div className="group relative inline-block">
                <Link
                  href="/"
                  className="hover:text-[#FB5C12] flex items-center gap-2 "
                >
                  <samp>ডেমো</samp>
                  <samp className=" group-hover:rotate-180 duration-300">
                    <MdKeyboardArrowUp />
                  </samp>
                </Link>
                <div className="group-hover:block hidden absolute w-fit bg-white">
                  <div>
                    <Link href="/"> কাস্টমার প্যানেল</Link>

                    <Link href="/">অ্যাডমিন প্যানেল</Link>
                  </div>
                </div>
              </div>
              <div className="group relative inline-block">
                <Link
                  href="/"
                  className=" flex items-center gap-2 hover:text-[#FB5C12] "
                >
                  <samp className=""> টুলস</samp>
                  <samp className=" group-hover:rotate-180 duration-300">
                    <MdKeyboardArrowUp />
                  </samp>
                </Link>
              </div>
            </div>

            <button className="hover:bg-[#FB5C12]  hover:text-white duration-200 cursor-pointer flex items-center gap-x-2 py-1 px-3 rounded-full outline-2 hover:outline-[#FB5C12] text-[#FB5C12]">
              <span>
                <FiPhone />
              </span>
              যোগাযোগ
            </button>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
